# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Force prompt to stay on one line: directory + character (your $)
format = "$directory$character"

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[\$](bold green)'
error_symbol = '[\$](bold red)'
# Disable prompt continuation symbol (in case you have multi-line commands)

# Directory path formatting: Truncate to last 4 folders, prefix with …/
[directory]
truncation_length = 7
#truncation_symbol = "…/"
home_symbol = "~"
truncate_to_repo = true
#style = "cyan"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
